; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Cultris 2 Patch"
#define MyAppVersion "v1.0.17"
#define MyAppPublisher "zDEFz, Shayklos. alfrix, Mekambe"
#define MyAppURL "https://github.com/zDEFz/c2-patch"
#define MyAppExeName "launcher.exe"

[Setup]
AppId={{38281810-7E78-4C0C-8518-C2328ED7A8E6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Cultris-2-Patch
DisableDirPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=C:\Users\mekambe\Desktop\c2-patch-aur\license.txt
OutputBaseFilename=cultris2-patch
SetupIconFile=C:\Users\mekambe\Desktop\c2-patch-aur\icons\ico\cultris2-icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\mekambe\Desktop\c2-patch-aur\launcher\bin\Release\net9.0-windows\win-x64\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Cultris2\bin\Cultris2-Colorpicker.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Cultris2\bin\Cultris2-Patch.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\Program Files (x86)\Cultris2\bin\Cultris2-Settings.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\Users\mekambe\Desktop\c2-patch-aur\resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\mekambe\Desktop\c2-patch-aur\settings\*"; DestDir: "{app}\settings"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  JDK_URL = 'https://api.adoptium.net/v3/installer/latest/17/ga/windows/x64/jdk/hotspot/normal/eclipse?project=jdk';
  JDK_OUTPUT = ExpandConstant('{tmp}\jdk-installer.msi');
  JDK_INSTALL_DIR = ExpandConstant('{app}\resources\jdk');

procedure DownloadJDK();
var
  ResultCode: Integer;
begin
  // Notify user of JDK installation
  MsgBox('Downloading and installing Java JDK 17. Please wait...', mbInformation, MB_OK);

  // Download JDK Temurin 17
  if not DownloadFile(JDK_URL, JDK_OUTPUT) then
  begin
    MsgBox('Failed to download JDK. Please check your internet connection.', mbError, MB_OK);
    Abort;
  end;

  // Install JDK silently in specified directory
  if not ShellExec('', 'msiexec.exe', '/i "' + JDK_OUTPUT + '" INSTALLDIR="' + JDK_INSTALL_DIR + '" /quiet /norestart', '', SW_SHOWNORMAL, ewWaitUntilTerminated, ResultCode) then
  begin
    MsgBox('Failed to install JDK.', mbError, MB_OK);
    Abort;
  end;

  // Set JAVA_HOME and add to system PATH
  RegWriteStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'JAVA_HOME', JDK_INSTALL_DIR);
  RegWriteStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'Path', JDK_INSTALL_DIR + '\bin');
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
  begin
    DownloadJDK();
  end;
end;
