<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <ApplicationIcon>icon/cultris2-icon.ico</ApplicationIcon>
  </PropertyGroup>

<ItemGroup>
  <None Include="icon\cultris2-icon.ico">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>


</Project>